global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'leaderboard-api'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

